######################################################################
# Automatically generated by qmake (2.01a) dg. de febr. 10 10:22:42 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += cppQt.cpp
